### ISSUE TITLE
Travis and Coveralls.io support

### ISSUE THREAD

**Issue by sobolevn** [sntran/ueberauth_auth0#10]
Could you please enable https://travis-ci.org/ and https://coveralls.io/ ?

Refs #9

**Comment by sntran** [comment]
I have enabled both for this repo. Let me know if you need anything else.

**Comment by sobolevn** [comment]
Thanks!

**Comment by lpil** [comment]
Time to close this issue? :)

**Comment by lpil** [comment]
Ah, actually now I look I see travis has not yet been configured. A PR will be needed for this.

**Comment by achedeuzot** [comment]
The PR #74 adds travis and coveralls integration. For now, there are no tests yet so the coveralls report is quite sad. It shall be fixed in the next releases.

**Comment by achedeuzot** [comment]
Travis & Coveralls have been added to the repo so I'll be closing this issue. The code coverage is still at 0% for now (as there are no tests, yet).
