### ISSUE TITLE
Nil value for uid_field

### ISSUE THREAD

**Issue by willykaram** [sntran/ueberauth_auth0#13]
I tried implementing the module as part of an overall Ueberauth, Guardian & Canary implementation. But I was getting an error on the callback indicating:

`nil given for :uid. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.uid)`

The error appears to be arising due to the fact that line 21 of `ueberauth_auth0/lib/ueberauth/strategy/auth0.ex` is set as follows: `uid_field: :user_id`.

However, I don't think that `user_id` is set anywhere in the strategy or a value available from Auth0.

I've set it as follows instead: `uid_field: :email`, which seems to resolve this issue. 

How did you work around this @sntran? Has anyone else encountered the issue? 

I'll submit a PR for the above in case it's of use.

BTW, I'm running elixir 1.5 and Phoenix 1.3.

**Comment by sntran** [comment]
Hi there,

Yes, the `user_id` was missing, and there was a PR here https://github.com/sntran/ueberauth_auth0/pull/12.

Let me publish a new version for this.

**Comment by willykaram** [comment]
Update to the above. I just reviewed the code on the github repo, and see there that the value is set to: `uid_field: :sub` instead over `:user_id`, and that value also seems to work.

I see that was resolved in PR #12

**Comment by willykaram** [comment]
Thank for the speedy reply :) ... you were replying just as I did. I saw that PR when I was trying to create something similar. Sorry for the distraction.

Please LMK if there's anything I can do to assist with documentation or development.

I'm writing an authentication guide for Elixir/Phoenix, and will be sure to cover this package. So hopefully that will help in terms of some supplemental documentation/screencast.

Thanks for your wonderful work/contribution.

**Comment by sntran** [comment]
No worry.

If you find typo or something that needs clarification in the document, or bugs in the codes, or enhancement, please contribute.
