### ISSUE TITLE
Integrate dependabot

### ISSUE THREAD

**Issue by sobolevn** [sntran/ueberauth_auth0#16]
Dependabot is an awesome tool to bump your dependencies automatically.

That's how it works: https://github.com/sobolevn/recase/pulls?q=is%3Apr+author%3Aapp%2Fdependabot
That's a lifesaver for some periodic update tasks.

@sntran could you please switch it on? I guess I am limited in my access rights. 
Here's a [how-to](https://dependabot.com/#how-it-works). Thanks!

**Comment by sntran** [comment]
Do we have enough tests to ensure bumping dependencies every time will not cause any issue?

**Comment by sobolevn** [comment]
Nope, but that on our list too: #7

**Comment by sntran** [comment]
[Look at that](https://github.com/sntran/ueberauth_auth0/pulls)!

**Comment by sobolevn** [comment]
There are many updates!

**Comment by sntran** [comment]
@sobolevn Would you mind checking whether those newer version of dependencies won't break? They are mostly for testing.

**Comment by sobolevn** [comment]
Sorry, I am quite busy with my primary job right now.
Maybe in two weeks or so. Is it fine?

**Comment by sntran** [comment]
No worry. I will pull them down and run the tests tonight. If everything passes, I'll merge.
