### ISSUE TITLE
How to sign out

### ISSUE THREAD

**Issue by lpil** [sntran/ueberauth_auth0#27]
Hello!

Thanks for the plugin. Does it provide functionality for logging out users? I was unable to find it.

Cheers,
Louis

**Comment by sntran** [comment]
👋 @lpil (I use your `mix test.watch`).

Überauth only provides the initial authentication challenge. The application handles the token issued by third party. Therefore, no logout functionality is defined here.

**Comment by lpil** [comment]
Thanks sntran :)

+ glad you're enjoying the test.watch lib!
