### ISSUE TITLE
OAuth2 Client serializer not set correctly

### ISSUE THREAD

**Issue by hez** [sntran/ueberauth_auth0#55]
Looks like when trying to use Jason as the encoder the option does not make its way down to the `OAuth2.Client` correctly.

I get the following if I do not include Poison in my dependancies

```
** (UndefinedFunctionError) function Poison.decode!/1 is undefined (module Poison is not available)
Poison.decode!("{\"access_token\":\"...\",\"id_token\":\"...\",\"scope\":\"openid profile email\",\"expires_in\":86400,\"token_type\":\"Bearer\"}")
(oauth2) lib/oauth2/response.ex:32: OAuth2.Response.new/3
(oauth2) lib/oauth2/request.ex:80: OAuth2.Request.process_body/3
(oauth2) lib/oauth2/client.ex:231: OAuth2.Client.get_token/4
(oauth2) lib/oauth2/client.ex:246: OAuth2.Client.get_token!/4
(ueberauth_auth0) lib/ueberauth/strategy/auth0.ex:49: Ueberauth.Strategy.Auth0.handle_callback!/1
(ueberauth) lib/ueberauth/strategy.ex:307: Ueberauth.Strategy.run_callback/2
```

The serializer appears to be configurable: https://github.com/scrogson/oauth2#configure-a-serializer

**Comment by sntran** [comment]
Thanks for reporting!

The change from `oauth2` puts me in a weird situation. Now that a JSON serializer is not included in `oauth`, but rather needed to be specified, I will need to do the same for this library, as I don't want to choose **one** JSON serializer as a dependency.

Now the user is required to include a JSON serializer as a dependency, and indicate it in config. Even though it gives them a choice, it kinda becomes a hassle. Maybe the user already uses `jason` for other purposes so it is fine for them, but not all apps need a JSON serializer.

There may be no other choice for me, but give me some time to think about this.

**Comment by hez** [comment]
@sntran understandable. Sadly it appears to be the way everything is going right now, thinking of Phoenix, Ecto, etc.

UeberAuth already has a setting for the json parser, probably best just to reuse that.

re: https://github.com/ueberauth/ueberauth#customizing-json-serializer

**Comment by achedeuzot** [comment]
The PR #74 adds the JSON serializer configuration from Ueberauth as well as a way to override the `serializers` of `OAuth`,

**Comment by achedeuzot** [comment]
@sntran & @hez : I suggest closing this issue as it's been resolved by the latest master. It may be a good time to release the latest version of the package (0.4.0)

**Comment by sntran** [comment]
@achedeuzot Yep, this is resolved.
