### ISSUE TITLE
Updated fork and maintainer available

### ISSUE THREAD

**Issue by achedeuzot** [sntran/ueberauth_auth0#73]
Hello,

I'll be needing this plugin extensively so I've already created an updated fork, for now, available here: https://github.com/vivakit/ueberauth_auth0

If the maintainers are around, I'd be happy to join the maintainers of this project, remove my separate fork and merge my updates into this project :)

Best regards,

@achedeuzot

**Comment by sntran** [comment]
Awesome! Thank you for doing that!

If you can take a look at the issues and PR, you can definitely maintain this repo. Right now my life has a new turn so my time is limited. I really want to resolve those issues and PR, but I haven't used Ueberauth or Auth for a long time, so I don't have a good set up to debug and fix.

**Comment by achedeuzot** [comment]
Hi there! Awesome.

No problem for looking at the issues and PRs. I just won't be able to do more than just comment on them for now as I don't have more rights. For most package update issues, it's already fixed on my fork.
I'll look at the other issues soon :)

**Comment by achedeuzot** [comment]
For now, I've moved my changes to a branch on my fork (`big-update`) and opened a PR #74 Tell me what you think.

**Comment by achedeuzot** [comment]
This has been solved. Closing :)
