### ISSUE TITLE
0.4 Hex pkg?

### ISSUE THREAD

**Issue by MasonLS** [sntran/ueberauth_auth0#94]
Is there a reason v0.4 isn't published on Hex? Just trying to avoid an unversioned github dependency here...

**Comment by hez** [comment]
Is it possible to release this?

**Comment by sntran** [comment]
@achedeuzot Is everything good for a new release to Hex?

**Comment by achedeuzot** [comment]
@sntran yep, it should be good for a release 👍

**Comment by sntran** [comment]
@MasonLS , @hez , @achedeuzot [v0.4.0](https://hex.pm/packages/ueberauth_auth0/0.4.0) has been published to hex.
